# Generated by Django 4.1.3 on 2022-11-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_register', '0002_remove_note_author_note_authorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='authorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_register.author'),
        ),
    ]
